defmodule TdDfLib.Validation do
  @moduledoc """
  Template content validation support.
  """

  alias Ecto.Changeset
  alias TdCache.HierarchyCache
  alias TdCache.Templates.AclLoader
  alias TdDfLib.Format
  alias TdDfLib.Parser
  alias TdDfLib.Templates

  @types %{
    "string" => :string,
    "boolean" => :boolean,
    "url" => :map,
    "user" => :string,
    "enriched_text" => :map,
    "table" => :map,
    "dynamic_table" => :map,
    "integer" => :integer,
    "float" => :float,
    "system" => :map,
    "copy" => :string,
    "domain" => :integer,
    "hierarchy" => :string
  }

  @allowed_origins ["user", "ai", "default", "autogenerated", "file"]
  @role_based_types ~w(user user_group)

  def build_changeset(content, content_schema, opts \\ []) do
    changeset_fields = get_changeset_fields(content_schema)
    content_values = Parser.get_from_content(content, "value")
    content_origins = Parser.get_from_content(content, "origin")

    {content_values, changeset_fields}
    |> Changeset.cast(content_values, Map.keys(changeset_fields))
    |> add_content_validation(content_schema, opts)
    |> add_origin_validations(content_origins)
  end

  defp get_changeset_fields(content_schema) do
    Map.new(content_schema, fn item ->
      name = Map.get(item, "name")
      type = Map.get(@types, Map.get(item, "type"), :string)
      cardinality = Map.get(item, "cardinality")
      {String.to_atom(name), get_field_type(type, cardinality)}
    end)
  end

  defp get_field_type(type, "*"), do: {:array, type}
  defp get_field_type(type, "+"), do: {:array, type}
  defp get_field_type(type, _), do: type

  defp dependent?(to_be, [_ | _] = dependent_value) do
    MapSet.new(to_be)
    |> MapSet.intersection(MapSet.new(dependent_value))
    |> MapSet.to_list()
    |> then(&(not Enum.empty?(&1)))
  end

  defp dependent?(to_be, dependent_value), do: Enum.member?(to_be, dependent_value)

  # Filters schema for non applicable dependant field
  defp add_content_validation(
         changeset,
         %{"depends" => %{"on" => on, "to_be" => to_be}} = field_spec,
         opts
       ) do
    dependent_value = Changeset.get_field(changeset, on)

    if dependent?(to_be, dependent_value) do
      add_content_validation(changeset, Map.drop(field_spec, ["depends"]), opts)
    else
      changeset
    end
  end

  # Filters schema for switch applicable dependant field
  defp add_content_validation(
         changeset,
         %{"name" => name, "values" => %{"switch" => %{"on" => on, "values" => to_be}}},
         _opts
       ) do
    dependent_value = Changeset.get_field(changeset, on)

    case Map.get(to_be, dependent_value) do
      nil ->
        changeset

      values when is_list(values) ->
        Changeset.validate_inclusion(changeset, String.to_atom(name), values)
    end
  end

  defp add_content_validation(changeset, %{} = field_spec, opts) do
    changeset
    |> add_require_validation(field_spec)
    |> add_inclusion_validation(field_spec, opts)
    |> add_image_validation(field_spec)
    |> add_richtext_validation(field_spec)
    |> add_url_validation(field_spec)
    |> add_content_errors(field_spec)
    |> add_hierarchy_depth_validation(field_spec)
    |> add_table_validation(field_spec, opts)
  end

  defp add_content_validation(changeset, [], _opts), do: changeset

  defp add_content_validation(changeset, [head | tail], opts) do
    changeset
    |> add_content_validation(head, opts)
    |> add_content_validation(tail, opts)
  end

  defp add_hierarchy_depth_validation(
         changeset,
         %{
           "values" => %{"hierarchy" => hierarchy},
           "type" => "hierarchy",
           "name" => field_name
         }
       ) do
    value_or_values_or_error = changeset |> Map.get(:data) |> Map.get(field_name)

    valid_depth? =
      case value_or_values_or_error do
        {:error, _} ->
          true

        [{:error, _} | _] ->
          true

        value ->
          hierarchy_id = Map.get(hierarchy, "id")
          min_depth = Map.get(hierarchy, "min_depth", 0)
          {:ok, hierarchy} = HierarchyCache.get(hierarchy_id)
          validate_hierarchy_depth(hierarchy, value, min_depth)
      end

    if valid_depth? do
      changeset
    else
      Changeset.add_error(changeset, String.to_atom(field_name), "incorrect depth")
    end
  end

  defp add_hierarchy_depth_validation(changeset, _), do: changeset

  def validate_hierarchy_depth(hierarchy, keys, depth \\ 0)

  def validate_hierarchy_depth(hierarchy, keys, depth) when is_binary(depth) do
    case {depth, Integer.parse(depth)} do
      {"", _} -> validate_hierarchy_depth(hierarchy, keys)
      {_, {int_depth, _}} -> validate_hierarchy_depth(hierarchy, keys, int_depth)
      _ -> false
    end
  end

  def validate_hierarchy_depth(hierarchy, keys, depth) when is_list(keys) do
    Enum.all?(keys, &validate_hierarchy_depth(hierarchy, &1, depth))
  end

  def validate_hierarchy_depth(_, nil, _), do: true
  def validate_hierarchy_depth(_, "", _), do: true

  def validate_hierarchy_depth(%{nodes: nodes} = _hierarchy, key, depth) do
    case Enum.find(nodes, &(Map.get(&1, "key") == key)) do
      nil ->
        false

      node ->
        node_depth = max((Map.get(node, "path") |> String.split("/") |> Enum.count()) - 2, 0)
        node_depth >= depth
    end
  end

  defp add_content_errors(
         %{valid?: false, errors: _errors, data: data} = changeset,
         %{"name" => name} = field_spec
       ) do
    case Map.get(data, name) do
      [_ | _] = list ->
        error = Enum.find(list, &match?({:error, _}, &1))

        case error do
          nil ->
            changeset

          {:error, error} ->
            add_content_error(changeset, field_spec, error)
        end

      {:error, error} ->
        add_content_error(changeset, field_spec, error)

      _ ->
        changeset
    end
  end

  defp add_content_errors(changeset, _), do: changeset

  defp add_content_error(
         changeset,
         %{"type" => "hierarchy", "name" => name},
         [%{"name" => node_name} | _]
       ) do
    error = {"has more than one node #{node_name}"}
    insert_error_in_changeset(changeset, error, name)
  end

  defp add_content_error(
         changeset,
         %{"type" => "hierarchy", "name" => name},
         :not_found
       ) do
    error = {"hierarchy"}
    insert_error_in_changeset(changeset, error, name)
  end

  defp add_content_error(changeset, %{"name" => name}, error),
    do: insert_error_in_changeset(changeset, error, name)

  defp insert_error_in_changeset(changeset, error, name) when is_binary(name),
    do: insert_error_in_changeset(changeset, error, String.to_atom(name))

  defp insert_error_in_changeset(changeset, error, name) when is_atom(name) do
    update_in(
      changeset.errors,
      &Enum.map(&1, fn
        {^name, {"is invalid", _error_type}} ->
          {name, error}

        {_key, _error} = tuple ->
          tuple
      end)
    )
  end

  defp add_require_validation(changeset, %{"name" => name, "cardinality" => "1"}) do
    validate_single(name, changeset)
  end

  defp add_require_validation(changeset, %{"name" => name, "cardinality" => "+"}) do
    validate_multiple(name, changeset)
  end

  defp add_require_validation(
         changeset,
         %{"mandatory" => %{"on" => on, "to_be" => target = [_ | _]}} = field
       ) do
    dependent = Changeset.get_field(changeset, on)

    if Templates.meets_dependency?(dependent, target) do
      validate_required_field(changeset, field)
    else
      changeset
    end
  end

  defp add_require_validation(changeset, %{
         "type" => "table",
         "name" => name,
         "values" => %{"table_columns" => columns}
       }) do
    field = String.to_atom(name)

    mandatory_columns = columns |> Enum.filter(& &1["mandatory"]) |> Enum.map(& &1["name"])

    changeset
    |> Changeset.get_change(field, [])
    |> Enum.with_index(&columns_with_errors(&2, &1, mandatory_columns))
    |> List.flatten()
    |> Enum.group_by(&elem(&1, 0), &elem(&1, 1))
    |> then(fn
      errors = %{} when map_size(errors) > 0 ->
        Enum.reduce(errors, changeset, fn {column_name, rows}, changeset ->
          Changeset.add_error(
            changeset,
            field,
            "#{column_name} can't be blank",
            validation: :required,
            rows: rows
          )
        end)

      _errors ->
        changeset
    end)
  end

  defp add_require_validation(changeset, %{}), do: changeset

  defp add_inclusion_validation(
         changeset,
         %{"name" => name, "values" => %{"fixed" => fixed}},
         _opts
       ) do
    validate_inclusion(changeset, name, fixed)
  end

  defp add_inclusion_validation(
         changeset,
         %{"name" => name, "values" => %{"fixed_tuple" => fixed_tuple}},
         _opts
       ) do
    fixed = Enum.map(fixed_tuple, &Map.get(&1, "value"))
    validate_inclusion(changeset, name, fixed)
  end

  defp add_inclusion_validation(
         changeset,
         %{"name" => name, "values" => %{"domain" => domain_values = %{}}},
         opts
       ) do
    field = String.to_atom(name)

    case take_domain_values(domain_values, opts[:domain_id], opts[:domain_ids]) do
      [_ | _] = available -> validate_inclusion(changeset, name, available)
      _ -> Changeset.delete_change(changeset, field)
    end
  end

  defp add_inclusion_validation(changeset, %{"name" => name, "type" => type} = definition, opts)
       when type in @role_based_types do
    domain_ids = fetch_domain_ids(opts)

    case domain_ids do
      [] ->
        Changeset.add_error(changeset, String.to_atom(name), "missing domains")

      [_ | _] = domain_ids ->
        role_value_inclusion_validation(changeset, definition, domain_ids)
    end
  end

  defp add_inclusion_validation(changeset, %{}, _opts), do: changeset

  defp role_value_inclusion_validation(
         changeset,
         %{"name" => name, "type" => "user", "values" => %{"role_users" => role_users}},
         domain_ids
       ) do
    user_names = fetch_user_names(domain_ids, role_users)
    validate_inclusion(changeset, name, user_names)
  end

  defp role_value_inclusion_validation(
         changeset,
         %{"name" => name, "type" => "user_group", "values" => %{"role_groups" => role_groups}},
         domain_ids
       ) do
    user_names = domain_ids |> fetch_user_names(role_groups) |> Enum.map(&"user:#{&1}")
    groups = domain_ids |> fetch_group_names(role_groups) |> Enum.map(&"group:#{&1}")

    validate_inclusion(changeset, name, groups ++ user_names)
  end

  defp role_value_inclusion_validation(changeset, %{}, _domain_ids), do: changeset

  defp take_domain_values(%{} = _domain_values, nil, nil), do: :none

  defp take_domain_values(%{} = domain_values, nil, domain_ids) do
    keys = Enum.map(domain_ids, &Format.to_string_format/1)

    domain_values
    |> Map.take(keys)
    |> Map.values()
    |> Enum.flat_map(& &1)
    |> Enum.uniq()
  end

  defp take_domain_values(%{} = domain_values, domain_id, domain_ids) do
    take_domain_values(domain_values, nil, [domain_id | List.wrap(domain_ids)])
  end

  defp add_image_validation(changeset, %{"name" => name, "type" => "image"}) do
    field = String.to_atom(name)
    Changeset.validate_change(changeset, field, &image_validation/2)
  end

  defp add_image_validation(changeset, %{}), do: changeset

  defp add_richtext_validation(changeset, %{"name" => name, "type" => "enriched_text"}) do
    field = String.to_atom(name)
    Changeset.validate_change(changeset, field, &validate_safe/2)
  end

  defp add_richtext_validation(changeset, %{}), do: changeset

  defp add_url_validation(changeset, %{"name" => name, "type" => "url"}) do
    field = String.to_atom(name)
    Changeset.validate_change(changeset, field, &validate_safe/2)
  end

  defp add_url_validation(changeset, %{}), do: changeset

  defp validate_no_empty_items(field, [_h | _t] = values) do
    case Enum.any?([nil, "", []], &Enum.member?(values, &1)) do
      true -> Keyword.new([{field, {"should not contain empty values", validation: :required}}])
      _ -> []
    end
  end

  defp validate_no_empty_items(field, %{} = values) do
    case values == %{} do
      true -> Keyword.new([{field, {"map should not be empty", validation: :required}}])
      _ -> []
    end
  end

  defp validate_no_empty_items(_, _), do: []

  defp image_validation(_field, nil), do: []

  defp image_validation(field, image_data) do
    {start, _length} = :binary.match(image_data, ";base64,")
    type = :binary.part(image_data, 0, start)

    case Regex.match?(~r/(jpg|jpeg|png|gif)/, type) do
      true -> []
      _ -> Keyword.new([{field, "invalid image type"}])
    end
  end

  defp validate_required_field(changeset, %{"name" => name, "cardinality" => "*"}) do
    validate_multiple(name, changeset)
  end

  defp validate_required_field(changeset, %{"name" => name, "cardinality" => "?"}) do
    validate_single(name, changeset)
  end

  defp validate_required_field(changeset, _field), do: changeset

  defp validate_multiple(name, changeset) do
    field = String.to_atom(name)

    changeset
    |> Changeset.validate_required(field)
    |> Changeset.validate_length(field, min: 1)
    |> Changeset.validate_change(field, &validate_no_empty_items/2)
  end

  defp validate_single(name, changeset) do
    field = String.to_atom(name)

    changeset
    |> Changeset.validate_required(field)
    |> Changeset.validate_change(field, &validate_no_empty_items/2)
  end

  defp validate_inclusion(%{data: data} = changeset, name, items) do
    field = String.to_atom(name)

    case Map.get(data, name) do
      l when is_list(l) -> Changeset.validate_subset(changeset, field, items)
      _not_list -> Changeset.validate_inclusion(changeset, field, items)
    end
  end

  defp fetch_domain_ids(opts) do
    [opts[:domain_id] | opts[:domain_ids] || []] |> Enum.filter(& &1) |> Enum.uniq()
  end

  defp fetch_user_names(domain_ids, role) do
    domain_ids
    |> AclLoader.get_roles_and_users()
    |> Map.get(role, [])
    |> Enum.map(& &1.full_name)
  end

  defp fetch_group_names(domain_ids, role) do
    domain_ids
    |> AclLoader.get_roles_and_groups()
    |> Map.get(role, [])
    |> Enum.map(& &1.name)
  end

  @doc """
  Returns a 2-arity validator function that can be used by
  `Ecto.Changeset.validate_change/3` on a dynamic content field. The argument
  may be either the name of a template or it's flattened schema, as returned by
  `Templates.content_schema/1`.
  """
  def validator(template_or_schema, opts \\ [])

  def validator({:error, reason}, _opts) do
    fn field, _value ->
      [{field, {"invalid template", [reason: reason]}}]
    end
  end

  def validator(template, opts) when is_binary(template) do
    template
    |> Templates.content_schema()
    |> validator(opts)
  end

  def validator(schema, opts) when is_list(schema) do
    fn field, value ->
      case build_changeset(value, schema, opts) do
        %{valid?: false, errors: errors} ->
          [{field, {format_validator_errors(errors), errors}}]

        _ ->
          validate_safe(field, value)
      end
    end
  end

  def validate_safe(field, value) when is_binary(value) do
    if String.contains?(value, "javascript:"), do: [{field, "invalid content"}], else: []
  end

  def validate_safe(field, value) when is_map(value) do
    formated_value =
      Map.new(value, fn
        {f, {:error, v}} ->
          {f, %{error: v}}

        v ->
          v
      end)

    validate_safe(field, Jason.encode!(formated_value))
  end

  def validate_safe(field, value) do
    validate_safe(field, Jason.encode!(value))
  end

  defp format_validator_errors(errors) when is_list(errors),
    do: Enum.map_join(errors, " - ", &format_validator_errors(&1))

  defp format_validator_errors({field, :no_translation_found}),
    do: "#{field}: translation not found"

  defp format_validator_errors({field, {msg, _}}) when is_binary(msg), do: "#{field}: #{msg}"

  defp format_validator_errors(_), do: "invalid content"

  defp add_origin_validations(changeset, origins) do
    origins
    |> Map.to_list()
    |> Enum.reduce(changeset, fn {key, value}, changeset ->
      if Enum.member?(@allowed_origins, value) do
        changeset
      else
        Changeset.add_error(changeset, String.to_atom(key), "invalid origin", origin: value)
      end
    end)
  end

  defp add_table_validation(
         changeset,
         %{"name" => name, "type" => "dynamic_table", "values" => %{"table_columns" => colums}},
         opts
       ) do
    field = String.to_atom(name)

    Changeset.validate_change(changeset, field, fn ^field, table_content_rows ->
      table_content_rows
      |> Enum.with_index(fn element, index -> {build_changeset(element, colums, opts), index} end)
      |> Enum.flat_map(&parse_row_errors(&1, field))
    end)
  end

  defp add_table_validation(changeset, _field_spec, _opts), do: changeset
  def allowed_origins, do: @allowed_origins

  defp parse_row_errors({%{valid?: true}, _index}, _field), do: []

  defp parse_row_errors({changeset, index}, field) do
    Enum.map(changeset.errors, fn {column, {error, validation}} ->
      extra = [row: index, column: column]

      {field,
       {"#{column} column in table row #{index}" <> " " <> "#{error}",
        Keyword.merge(validation, extra)}}
    end)
  end

  defp columns_with_errors(row, value, mandatory_columns) do
    mandatory_columns
    |> Enum.filter(fn column -> Map.get(value, column) in [nil, ""] end)
    |> Enum.map(fn column_name -> {column_name, row} end)
  end
end
